### ISSUE TITLE
Readme is not showing all the steps to setup the project

### ISSUE THREAD

**Issue by arielj** [rubyforgood/rubyforgood.org#17]
### It doesn't show which NodeJS version we should use (I found it in the `.tool-versions` file, but it should be there in the readme, next to the Ruby and Bundler versions).

One comment though on the Node version. I'm using the exact version of Node specified in that file, but when I run `npm install` it changes the `package.json` and `package-lock.json` trying to generate the lock file using `lockfileVersion: 2` instead of the current `lockfileVersion: 1`. I understand the `lockfileVersion: 1` is generated with older Node versions, so it's not clear if we should ignore that file change or if the node version in the `.tool-versions` file is not the correct one to use.

### It doesn't tell you to run `bundle install`, which you find out with an error when trying to run `npm run test`.

I can submit a PR with this changes, but I'm not sure what's the correct version of Node

**Comment by meg-gutshall** [comment]
Hi @arielj! Thank you for opening this issue! 

For the Node version, I will have to look into this further. We started the site from a template and made changes from there so I think I need to go in and clean up some of these packages before I can have a definite answer for you. As I said in my other comment, this site is still largely in MVP and I won't have time until September to get back into it, but I wanted to let you know I saw your issue.

My goal for September is to get the site to a clean v1 as a "Preptember" task and then create as many issues as I can find on the repo for Hacktoberfest. Documentation will be a **HUGE** part of this as well as cleaning up the styling.

If you're interested in helping me with this in any way, I would welcome it so much! Join our [Ruby for Good Slack](https://rubyforgood.herokuapp.com/) and DM me at Meg Gutshall. Of course, you're also welcome to contribute casually if you don't have the time to do any more than that!

**Comment by arielj** [comment]
Thanks! regarding the node version, if I use node 14 the package-lock.json is not updated to lockfileVersion: 2 (it does move one line in the package.json*). I imagine the 2 options are:
- instruct to use Node 14
- instruct to use Node 16 while updating the package-lock.json to lockfileVersion: 1

App works fine in both cases though.


* The line it changes in the package.json file is this:
![image](https://user-images.githubusercontent.com/188464/130541115-b1bd9d66-ce79-4c9b-96ed-600d60f00974.png)

It's just moving the line so `string_` comes before `string-`.

I'll join the slack group, thanks!

**Comment by meg-gutshall** [comment]
# Issue Tasks

- [ ] Update documentation to reflect the [correct Ruby, Bundler, and Node versions](https://github.com/rubyforgood/rubyforgood.org/commit/eb3534b71312a3c5bc63f2f810e540e5920ab045)
- [ ] Update documentation to add the `bundle install` step
- [ ] Research and update `package.json` dependencies and devDependencies
    - Remove unneeded packages from `package.json` file, delete the `package-lock.json` file and `node_modules/` directory, then run `npm install` to generate clean copies of the `package-lock.json` file and `node_modules/` directory.
