### ISSUE TITLE
Add Clickable Arrow to Our Supporters Slider on Home Page

### ISSUE THREAD

**Issue by designbygia** [rubyforgood/rubyforgood.org#2]
# Summary
Please add arrows on the Our Supporters slider on the Home page. Users can currently click and drag to advance the slider, but this is not intuitive and it would be very helpful to have an easier way to navigate the slider. 

This is the slider:
![image](https://user-images.githubusercontent.com/56228717/100891289-1dcaee80-3487-11eb-8b21-bddb1d1e41e2.png)

Please let me know if you have any questions! 

# Criteria for Completion
 
 - [ ] Visitors to the website can click on the arrows to advance the slider.

**Comment by meg-gutshall** [comment]
@designbygia, do you still want to enable autoplay on this slider?

**Comment by designbygia** [comment]
Hi @meg-gutshall ! Yes, would you please keep the auto-play and also add the arrows, so users can scroll through if they would like? Thanks!
