### ISSUE TITLE
Implement Flickity throughout Site

### ISSUE THREAD

**Issue by meg-gutshall** [rubyforgood/rubyforgood.org#54]
# Issue Summary

Right now, our site uses OwlCarousel2 and Slick to implement slider/carousel features. Both projects haven't been touched in a while, and we want to focus more on making the site navigable for our mobile users. Let's remove these older packages and use [Flickity](https://flickity.metafizzy.co/) instead.

## Sliders

Sliders that need to be addressed include:

- [ ] The hero slider on the home page
- [ ] The supporters slider on the home page
- [ ] The testimonial slider (not currently rendered on the site, but you can [find an example here](https://tradejk.netlify.app/))
- [ ] The project slider (not currently rendered on the site --> I'll get an example up soon)

They're located at `assets/js/main.js`. It would be great to have these cleaned up and organized within that file or possibly separated in their own file, depending on what seems better!

**Comment by grazirs** [comment]
Hi @meg-gutshall! Can I get this issue?

**Comment by meg-gutshall** [comment]
Why, yes, you can! 😆 Let me know if you have any questions or run into any blockers! I don't want you to feel on your own here. 😄 

Also, this is by no means time-sensitive. I cleaned up the repo a few nights ago, so please remember to pull the latest changes before you get going. 👍
